services:
  flight_service:
    build: ./flight_service
    container_name: flight_service
    ports:
      - "5001:5001"

  hotel_service:
    build: ./hotel_service
    container_name: hotel_service
    ports:
      - "5002:5002"

  car_service:
    build: ./car_service
    container_name: car_service
    ports:
      - "5003:5003"

  orchestrator:
    build: ./orchestrator
    container_name: orchestrator
    ports:
      - "5000:5000"
    depends_on:
      - flight_service
      - hotel_service
      - car_service
